[project]
name = 'stxflow-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Auto-refund]
path = 'contracts/Auto-refund.clar'
clarity_version = 1
epoch = 2.05

[contracts.escrow-contract]
path = 'contracts/escrow-contract.clar'
clarity_version = 3
epoch = 3.0

[contracts.loyalty-rewards]
path = 'contracts/loyalty-rewards.clar'
clarity_version = 3
epoch = 3.0

[contracts.payment-processing]
path = 'contracts/payment-processing.clar'
clarity_version = 3
epoch = 3.0

[contracts.receipt-token]
path = 'contracts/receipt-token.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
